spring:

#  h2:
#    console:
#      enabled: true
#      path: /h2


  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  #模板
  thymeleaf:
    cache: false

  #热更新
  devtools:
    livereload:
      enabled: true
#      http://stackoverflow.com/questions/35895730/spring-boot-devtools-static-content-reloading-does-not-work-in-intellij
#http://www.mkyong.com/spring-boot/intellij-idea-spring-boot-template-reload-is-not-working/
#http://javabeat.net/spring-boot-devtools/
#    restart:
#      additional-paths: src/main/resources/html/
  #多坏境配置
#  profiles:
#    active: dev

  resources:
       static-locations: classpath:/html/,classpath:/static/
  #es
  data:
    elasticsearch:
      properties:
       host: 127.0.0.1
       port: 9300
      cluster-name: es
#      cluster-nodes:未填写为客户端模式

#security:
#  user:
#    name: liuwp
#    password: 123456
#    role: admin
#日志
logging:
# level:
#     org.springframework.web: ERROR
#     com.mkyong: DEBUG
# pattern:
#     console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#     file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
# file: /application.log
server:
  port: 9999

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.liuwup.model